name: Bump version workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semver type of new version (major / minor / patch)'
        required: true
        type: choice
        options: 
        - patch
        - minor
        - major

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: Install the latest version of rye
      uses: eifinger/setup-rye@v4
    - name: bump version
      run: |
        rye version -b ${{ github.event.inputs.version }} #the action is not update the code
    - name: commit
      uses: EndBug/add-and-commit@v9
      with:
        message: "Bump version to ${{ github.event.inputs.version }}"
        add: 'pyproject.toml'
        author_name: "${GITHUB_ACTOR}"
        author_email: "${GITHUB_ACTOR}@atareao.es"

