name: Bump version workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semver type of new version (major / minor / patch)'
        required: true
        type: choice
        options: 
        - patch
        - minor
        - major

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: Install the latest version of rye
      uses: eifinger/setup-rye@v4
    - name: bump version
      run: |
        rye version -b ${{ github.event.inputs.version }} #the action is not update the code
    - name: commit
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Bump version to ${{ github.event.inputs.version }}"

