name: Bump version workflow

on:
  push:
    branches:
      - development

jobs:
  bump_version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
      with:
        ref: development
    - name: Get action from comments
      id: get_action
      run: |
        comments=$(git log --pretty=format:"%s" -1)
        echo $comments
        echo "comments=${comments}" >> $GITHUB_OUTPUT
        if [[ $comments =~ "\#major" ]]; then
          action="major"
        elif [[ $comments =~ "\#minor" ]]; then
          action="minor"
        elif [[ $comments =~ "\#patch" ]]; then
          action="patch"
        else
          action="none"
        fi
        echo "action=${action}" >> $GITHUB_OUTPUT
        echo "Selected action: ${action}"
    - name: Install the latest version of rye
      id: install_rye
      if: ${{ steps.get_action.outputs.action != 'none' }}
      uses: eifinger/setup-rye@v4
    - name: Get current version
      id: get_current_version
      if: ${{ steps.get_action.outputs.action != 'none' }}
      run: |
        current_version=$(rye version)
        echo "current_version=${current_version}" >> $GITHUB_OUTPUT
    - name: Merge development into main
      if: ${{ steps.get_action.outputs.action != 'none' }}
      run: |
        current_version=${{ steps.get_action.outputs.current_version }}
        git checkout main
        git pull origin main
        git merge --no-edit --no-ff development
        git push origin main
        git tag -a "$current_version" -m "Release ${current_version}" -s
        gh create release "${current_version}" --title "Release ${current_version}" --notes "Release ${current_version}"
    - name: bump version
      id: bump_version
      if: ${{ steps.get_action.outputs.action != 'none' }}
      run: |
        action=${{ github.get_action.outputs.action }}
        rye version -b $option
        new_version=$(rye version)
        echo "new_version=${new_version}" >> $GITHUB_OUTPUT
    - name: commit
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Bump version from ${{ steps.get_current_version.outputs.current_version}} to ${{ steps.bump_version.outputs.new_version }}"

