name: Bump version workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: 'Semver type of new version (major / minor / patch)'
        required: true
        type: choice
        options: 
        - patch
        - minor
        - major

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
      with:
        ref: development
    - name: Install the latest version of rye
      uses: eifinger/setup-rye@v4
    - name: bump version
      run: |
        option=${{ github.event.inputs.version }}
        if [[ -z "$option" ]]; then
          option=patch
        fi
        original_version=$(rye version)
        rye version -b $option
        new_version=$(rye version)
        echo "original_version=${original_version}" >> $GITHUB_ENV
        echo "new_version=${new_version}" >> $GITHUB_ENV
    - name: commit
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Bump version from ${{ env.original_version }} to ${{ env.new_version }}"
    - name: checkout repo
      uses: actions/checkout@v4
      with:
        ref: main
    - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    - name: get release version
      run: |
        release_version=$(rye version)
        echo "release_version=${release_version}" >> $GITHUB_ENV
        echo "Release version is ${{ env.release_version }}"
    - name: Release snapshot
      id: release-snapshot
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "v${{ env.release_version }}"
        release_name: "v${{ env.release_version }}"
        draft: false
        prerelease: false

