name: Bump version workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semver type of new version (major / minor / patch)'
        required: true
        type: choice
        options: 
        - patch
        - minor
        - major

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: Install the latest version of rye
      uses: eifinger/setup-rye@v4
    - name: Setup Git
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@atareao.es"
    - name: bump version
      run: |
        rye version -b ${{ github.event.inputs.version }} #the action is not update the code
        git add pyproject.toml
        git commit -m "Bump version to ${{ github.event.inputs.version }}"
        git push

